### ISSUE TITLE
API returning 520 for socket report create

### ISSUE THREAD

**Issue by aarongoldenthal** [SocketDev/socket-cli-js#95]
When running `socket report create` in GitLab CI, have recently had the CLI start to periodically return the following:

```sh
$ npm i -g @socketsecurity/cli@0.8.2
added 163 packages in 7s
64 packages are looking for funding
  run `npm fund` for details
$ socket report create . --view
- Creating report with 2 package files
✖ Unexpected error: Failed creating report: API returned an error: Response code 520 ()
ErrorWithCause: Failed creating report
    at handleApiCall (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/utils/api-helpers.js:38:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createReport (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/commands/report/create.js:[22](https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/jobs/5580572631#L22)4:18)
    at async Object.run (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/commands/report/create.js:44:31)
    at async meowWithSubcommands (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/utils/meow-with-subcommands.js:58:14)
    at async Object.run (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/commands/report/index.js:11:5)
    at async meowWithSubcommands (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/utils/meow-with-subcommands.js:58:14)
    at async file:///usr/local/lib/node_modules/@socketsecurity/cli/cli.js:18:3
caused by: ErrorWithCause: API returned an error
    at #handleApiError (/usr/local/lib/node_modules/@socketsecurity/cli/node_modules/@socketsecurity/sdk/index.js:251:15)
    at SocketSdk.createReportFromFilePaths (/usr/local/lib/node_modules/@socketsecurity/cli/node_modules/@socketsecurity/sdk/index.js:126:85)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleApiCall (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/utils/api-helpers.js:36:14)
    at async createReport (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/commands/report/create.js:2[24](https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/jobs/5580572631#L24):18)
    at async Object.run (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/commands/report/create.js:44:31)
    at async meowWithSubcommands (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/utils/meow-with-subcommands.js:58:14)
    at async Object.run (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/commands/report/index.js:11:5)
    at async meowWithSubcommands (file:///usr/local/lib/node_modules/@socketsecurity/cli/lib/utils/meow-with-subcommands.js:58:14)
    at async file:///usr/local/lib/node_modules/@socketsecurity/cli/cli.js:18:3
caused by: HTTPError: Response code 520 ()
    at Request.<anonymous> (file:///usr/local/lib/node_modules/@socketsecurity/cli/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:629:[26](https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/jobs/5580572631#L26))
    at Request.emit (node:events:526:35)
    at Request._onResponseBase (file:///usr/local/lib/node_modules/@socketsecurity/cli/node_modules/got/dist/source/core/index.js:7[27](https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/jobs/5580572631#L27):22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._onResponse (file:///usr/local/lib/node_modules/@socketsecurity/cli/node_modules/got/dist/source/core/index.js:766:13)
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
``` 

This has occurred with multiple Node projects on different days (e.g. [here](https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/jobs/5580572631), [here](https://gitlab.com/gitlab-ci-utils/gitlab-releaser/-/jobs/5580557477), and [here](https://gitlab.com/gitlab-ci-utils/ci-logger/-/jobs/5565446692)).

**Comment by mrfelpa** [comment]
Have you validated that your CI executor has the necessary network permissions to access the SocketSecurity API?

sometimes network problems or firewall settings can cause intermittent connectivity problems.

**Comment by aarongoldenthal** [comment]
Given the inconsistent nature on the same infrastructure on my end, I still think it was a problem on Socket's end. That said, I haven't seen it recur in several months, so I think it can be closed.
